version: '2'
services:

##MySQL Server
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nodejs
      MYSQL_DATABASE: nodejs

#Nginx Server
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www
    depends_on:
      - mysql
      - nodejs 
    links:
      - mysql
      - nodejs


##Node.js Server
  nodejs:
    build: .
    container_name: nodejs
    ports: 
      - "3000"
    volumes: 
      - "./nodesrc:/src"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: nodejs
    depends_on:
      - mysql
    links:
      - mysql
#    command:
#      - node /home/tlp/gitprojects/nginx-nodejs/nodesrc/app.js
#      - pwd
#      - pwd 
