version: '2'
services:


##Node.js Server
  nodejs:
    image: nginx
    container_name: nodejs
    ports: 
      - "80:80"
    volumes: 
      - ./html:/var/www
    environment:
      mysql_host: mysql
      mysql_user: root
      mysql_pass: nodejs
    depends_on:
      - mysql
    links:
      - mysql


##MySQL Server
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nodejs
      MYSQL_DATABASE: nodejs
